package:
  name: vtk
  version: "{{ vtk }}"

source:
  fn: VTK-{{ vtk }}.tar.gz
  url: http://www.vtk.org/files/release/8.1/VTK-{{ vtk }}.tar.gz

build:
  number: 1
  features:
    - vc9   # [win and py27]
    - vc14  # [win and (py35 or py36)]
  skip:
    - True  # [win and py27]
  skip_compile_pyc:
    - "*/*.py"   # [win]

requirements:
  build:
    - {{ compiler('c') }}   # [osx or win]
    - {{ compiler('cxx') }} # [osx or win]
    - python  {{ python }}
    - pkgconfig             # [unix]
    - ninja
    - cmake >=3.6 
    - git
    - setuptools            # [win]  
  host:
    - future
    - python {{ python }}
    - hdf5 1.8.18|1.8.18.*  # [unix]
    - zlib 1.2.*
    - setuptools            # [win]

  run:
    - python  {{ python }}
    - future 
    - hdf5 1.8.18|1.8.18.*  # [unix]
    - numpy
    - pillow
    - zlib 1.2.*
    
test:
  requires:
    - python {{ python }}
    - numpy
    - pillow
    - future
  imports:
    - vtk

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.
extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - rlizzo
    - lantiga
