#!/bin/bash

mkdir build
cd build

BUILD_CONFIG=Release

cmake .. \
    -Wno-dev \
    -DCMAKE_BUILD_TYPE:STRING=$BUILD_CONFIG \
    -DCMAKE_OSX_ARCHITECTURES:STRING=${OSX_ARCH} \
    -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX} \
    -DITK_USE_FLAT_DIRECTORY_INSTALL:BOOL=ON \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DBUILD_EXAMPLES:BOOL=OFF \
    -DBUILD_TESTING:BOOL=OFF \
    -DITK_USE_REVIEW:BOOL=ON \
    -DITK_USE_REVIEW_STATISTICS:BOOL=ON \
    -DITK_USE_OPTIMIZED_REGISTRATION_METHODS:BOOL=ON

make -j${CPU_COUNT}
make install