package:
  name: itk
  version: "{{ itk }}"

source:
  git_rev: v{{ itk }}
  git_url: https://github.com/Kitware/ITK.git

build:
  features:
    - vc14                    # [win and (py35 or py36)]  
  number: 2
  skip_compile_pyc:
    - "*/*.py"
  skip:
    - True                    # [win and py27]  

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake 
    - git
    - ninja 

about:
  home: https://itk.org/
  license: >
     See https://itk.org/ITK/project/license.html for details.
  summary: >
    ITK is an open-source, cross-platform C++ toolkit for segmentation and
    registration.

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    - rlizzo
    - lantiga
